### ISSUE TITLE
ADD 구현 관련해서 질문이 있습니다

### ISSUE THREAD

**Issue by evejaeyong** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#10]
ADD를 구현할 때, 인자 중 하나라도 존재하지 않을 시 에러 코드를 출력한다고 적혀있는데
그러면 인자가 더 많이 입력되는 경우는 고려하지 않는 것인지 궁금합니다.

감사합니다.

**Comment by KIMMINTAE98** [comment]
ADD 명령어를 동작하는데 필요한 인자가 부족한 경우만 고려해주시면 됩니다.
