### ISSUE TITLE
개월 관련 질문

### ISSUE THREAD

**Issue by aka-hub** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#11]
안녕하세요. 데이터구조설계 과목 수강하는 2021202029 이지연입니다.
실습 과목을 수강하지 않아 이곳에 질문 남깁니다. 
6개월의 경우 어떤 기준으로 측정되나요? 
단순히 달에 +6이라고 계산하나요? 
예를 들어 2023년 8월 30일에 6개월이 추가되었을 시에는 
2월 30일이라는 날짜가 없기에 그 월의 말일인 24년 2월 29일에 날짜가 만료되어야 하는 건가요? 
개월수에 대해서 명확한 기준이 없는 것 같아 문의드립니다.
감사합니다.

**Comment by KIMMINTAE98** [comment]
날짜 계산에 대해서는 다음과 같이

8월 31일에서 6개월뒤 -> 2월 31일(있는것으로 가정)
12월 31일에서 6개월뒤 -> 6월 31일(있는것으로 가정)

날짜 관련해서는 별도의 예외 처리하지 않고 해당 월에 매칭되는 일(ex. 31일)이 없어도 그냥 있는 것으로 가정하고 프로젝트 진행하시면 됩니다.
