### ISSUE TITLE
Member_Queue 구현 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by evejaeyong** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#2]
Queue의 크기를 100으로 초기화하고 Queue가 가득 차 있을 때 PUSH가 수행되는 경우 프로그램이 종료된다고 적혀 있습니다.
그런데 이 기준이 배열로 구현했을 경우 rear가 100인 경우 종료인지 size가 100인 경우 종료인지 궁금합니다.
감사합니다.

**Comment by KIMMINTAE98** [comment]
Queue 안에 원소가 100개 일 때 (size가 100인 경우) PUSH 수행 시 프로그램이 종료 되는 것으로 생각하고 구현하시면 됩니다.
