### ISSUE TITLE
TermsList 구현 관련 질문입니다.

### ISSUE THREAD

**Issue by ChoiEunchan** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#3]
안녕하세요. 프로젝트 구현 중에 질문 거리가 생겨서 질문 드립니다.
프로젝트 제안서에 따르면 TermsListNode class는
가입 약관 종류, 해당 가입 약관의 회원 수, 해당 가입 약관의 BST포인터 정보를 가진다고 나와있는데

1. TermsList의 헤드에 위의 정보들을 가지고 있고, 그 이후의 노드 들은 MemberQueueNode class에서와 같이
회원 정보를 저장하는 것을 뜻하시는 건가요? 아니면  회원 가입 정보에 위의 사항들이 추가되는 것으로 이해해야 할까요?

2. BST 포인터 정보라는 것이 만약 가입 약관 A의 BST가 있다면 List의 노드들이 BST의 자기 자신을 가리키는 것인지
아니면 자신이 속해있는 BST의 root node를 가리키는 것을 의미하는 것인지 궁금합니다.

감사합니다.

**Comment by KIMMINTAE98** [comment]
1. TermsList를 구성하는 TermsListNode는 "가입 약관 종류, 해당 가입 약관의 회원 수, 해당 가입 약관의 BST포인터 정보" 만 저장하며, 가입 약관 종류가 4종류이므로 최대 4개까지 존재할 수 있습니다.

2. TermsListNode들이 TermsList를 구성하고, TermsBSTNode들이 TermsBST를 구성합니다. 따라서 List의 노드들은 BST 내부에 속하지 않습니다. List의 노드 별로 각각 별도의  BST를 가지게되고, 해당 BST를 가리키는 포인터라고 생각하시면 됩니다.
