### ISSUE TITLE
TermList 구현 관련 질문입니다.

### ISSUE THREAD

**Issue by evejaeyong** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#4]
TermList 클래스에서 주석으로 search 함수를 구현하라는 듯이 적혀 있어서 질문 드립니다.

그런데 제가 이해한 바로는 NameBST 클래스에서만 Search를 사용하고, 다른 클래스에서는 필요 없다고 생각했습니다.
TermList의 Search 함수가 어떤 역할을 수행해야 하는지 알려주시면 감사하겠습니다!

**Comment by KIMMINTAE98** [comment]
스켈레톤 코드에 주석처리 된 함수들은 참고용으로 작성되었습니다.
해당 함수가 필요 없다고 판단되시면, 구현하지 않으셔도 됩니다.
