### ISSUE TITLE
Queue POP의 예외처리 관련 질문입니다.

### ISSUE THREAD

**Issue by PangDae20** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#5]
Program Implementation에서 Member Queue의 4번째 조건에서
- 큐가 비어 있을때 POP을 하거나 큐가 가득 차있을 때 PUSH를 하면 프로그램을 종료

라고  명시되어 있어 제가 이해하기론 exit 나 return과 같이 바로 프로그램을 종료하는 것으로 이해하고 있었습니다.

그런데 Functional Requirements에서는 QPOP을 설명하는 부분에서 
- Member_Queue에 데이터가 존재하지 않을 시 에러 코드를 출력한다.

라고 명시되어 있습니다. 

주어진 스켈레톤 코드에서 txt파일을 읽는 것에 실패하면 로그를 찍은 뒤에 exit()를 이용해 프로그램을 종료하는 것으로 주어져
저 역시 구현하면서 큐가 비어있을 때 pop을 한다면 큐가 비어있다는 로그를 찍고 exit()를 호출하였는데,
Functional Requirements에서는 에러코드를 출력한다고 나와 있습니다.

따라서 큐가 비어있을 때 pop을 하면 어떤 방식으로 예외 처리를 해야하는 지가 궁금하여 질문 드립니다.

**Comment by KIMMINTAE98** [comment]
Program Implementation에서 Member Queue의 4번째 조건에서
- 큐가 비어 있을때 POP을 하거나 큐가 가득 차있을 때 PUSH를 하면 프로그램을 종료

--> 해당 조건은 **초기에는 Queue에 데이터가 있어** 동작을 수행해 모든 데이터를 사용했는데,  계속 pop을 요청하는 경우를 방지하기 위한 조건입니다.

Functional Requirements에서는 QPOP을 설명하는 부분에서
- Member_Queue에 데이터가 존재하지 않을 시 에러 코드를 출력한다.

--> 해당 조건은 **초기부터 Queue에 아무 데이터가 없는 경우**에, OPOP을 실행했을 때 에러코드를 출력하는 조건입니다.
