### ISSUE TITLE
ADD 명령어 관련 질문입니다.

### ISSUE THREAD

**Issue by vamosdancar** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#6]
ADD 명령어의 경우 인자 중에 1개라도 존재하지 않은 경우 에러 코드를 출력해야 하는데, 

만약 가입 약관 종류가 누락된 경우 입력을 어느 형식으로 받는지 알고자 합니다.  

마지막 공백이 없는("ADD tom 50 2020-07-21") 형식인지 마지막 공백이 추가된 ("ADD tom 50 2020-07-21  ")형식인지 
아니면 관계 없는지 궁금합니다.

추가적으로 compile은 수행되나, #pragma once 경고가 발생하면 감점 사유인지 알고자 합니다.

**Comment by KIMMINTAE98** [comment]
1. 두 케이스 모두 약관 종류가 누락된 입력 형식으로 보시면 될 것 같습니다.

2. 컴파일하여 생성된 실행 파일이 정상적으로 동작하기만 하면 문제 없습니다.
