### ISSUE TITLE
과제 내 DELETE 명령어 구현 관련 질문

### ISSUE THREAD

**Issue by codml** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#7]
안녕하세요, 2020202034 김태완입니다. DELETE 명령어 구현 관련해서 질문 사항이 있습니다.
과제 내 자료구조 중 TermsBST에서 노드를 추가할 때 '개인정보만료일자가 이전인 노드는 왼쪽, 같거나 이후인 노드는 오른쪽 서브 트리에 위치한다'고 써 있습니다. 여기서 '이전'을 처음엔 사전적 정의로 생각해 '날짜가 같거나 전'이라고 생각했는데, 뒤 내용에 '같거나 이후인 노드는 오른쪽'이라는 내용이 있어 '날짜가 전'이라고 생각했습니다.
그런데 DELETE애도 '해당 일자보다 개인정보만료일자가 이전인 모든 노드들을 제거한다'는 문구가 있어 이것의 의미가 '날짜가 전'인 노드를 삭제하는 건지, '날짜가 같거나 전'인 노드를 삭제하는 건지 궁금합니다!
예를 들어, 'DELETE DATE 2024-05-12'를 입력하였을 때 개인정보만료일자가 2024-05-12인 노드를 삭제해야 하는 지를 모르겠다는 뜻입니다!

**Comment by KIMMINTAE98** [comment]
'날짜가 전'인 노드를 삭제하도록 구현해 주시면 됩니다.

'DELETE DATE 2024-05-12'를 입력하였을 때 개인정보만료일자가 2024-05-12인 노드는 삭제되지 않습니다.
