### ISSUE TITLE
스켈레톤 코드관련 질문

### ISSUE THREAD

**Issue by hdh3665** [KIMMINTAE98/2023_Kwangwoon_Univ_CE_DS_Project_1#8]
안녕하세요 2022202076 홍동현입니다. 과제를 수행하던 중 스켈레톤 코드에서 반환 타입이 void 형으로 되어있던 함수면 임의로 int형이나 다른 type으로 변경해서 사용해도 되는지 궁금합니다. 또, 함수 인자 등 함수 이름을 건드리지 않는 선에서 변경이 가능한지 질문드립니다.

**Comment by KIMMINTAE98** [comment]
클래스 이름과 프로그램 구조를 변경하지 않는 선에서, 
함수 명, 인자, 반환형 등은 자유롭게 구현 가능합니다.
